In [58]:
import os
print(os.getcwd())
%cd ../Data

d:\Pandas and Numpy\Data
d:\Pandas and Numpy\Data

In [59]:
import pandas as pd 
import numpy as np
df = pd.read_csv("time_series_covid19_confirmed_global.csv")
df.head(5)

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,2/28/23,3/1/23,3/2/23,3/3/23,3/4/23,3/5/23,3/6/23,3/7/23,3/8/23,3/9/23
0,NaN,Afghanistan,33.93911,67.709953,0,0,0,0,0,0,...,209322,209340,209358,209362,209369,209390,209406,209436,209451,209451
1,NaN,Albania,41.15330,20.168300,0,0,0,0,0,0,...,334391,334408,334408,334427,334427,334427,334427,334427,334443,334457
2,NaN,Algeria,28.03390,1.659600,0,0,0,0,0,0,...,271441,271448,271463,271469,271469,271477,271477,271490,271494,271496
3,NaN,Andorra,42.50630,1.521800,0,0,0,0,0,0,...,47866,47875,47875,47875,47875,47875,47875,47875,47890,47890
4,NaN,Angola,-11.20270,17.873900,0,0,0,0,0,0,...,105255,105277,105277,105277,105277,105277,105277,105277,105288,105288

In [60]:
df.info()
df.shape

<class 'pandas.DataFrame'>
RangeIndex: 289 entries, 0 to 288
Columns: 1147 entries, Province/State to 3/9/23
dtypes: float64(2), int64(1143), str(2)
memory usage: 2.5 MB

(289, 1147)

In [61]:
df["Province/State"].isnull().sum()

np.int64(198)

In [62]:
df["Country/Region"].nunique()

201

In [63]:
df[df["Country/Region"].duplicated(keep=False)]

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,2/28/23,3/1/23,3/2/23,3/3/23,3/4/23,3/5/23,3/6/23,3/7/23,3/8/23,3/9/23
9,Australian Capital Territory,Australia,-35.473500,149.012400,0,0,0,0,0,0,...,232018,232018,232619,232619,232619,232619,232619,232619,232619,232974
10,New South Wales,Australia,-33.868800,151.209300,0,0,0,0,3,4,...,3900969,3900969,3908129,3908129,3908129,3908129,3908129,3908129,3908129,3915992
11,Northern Territory,Australia,-12.463400,130.845600,0,0,0,0,0,0,...,104931,104931,105021,105021,105021,105021,105021,105021,105021,105111
12,Queensland,Australia,-27.469800,153.025100,0,0,0,0,0,0,...,1796633,1796633,1800236,1800236,1800236,1800236,1800236,1800236,1800236,1800236
13,South Australia,Australia,-34.928500,138.600700,0,0,0,0,0,0,...,880207,880207,881911,881911,881911,881911,881911,881911,881911,883620
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
274,Montserrat,United Kingdom,16.742498,-62.187366,0,0,0,0,0,0,...,1403,1403,1403,1403,1403,1403,1403,1403,1403,1403
275,Pitcairn Islands,United Kingdom,-24.376800,-128.324200,0,0,0,0,0,0,...,4,4,4,4,4,4,4,4,4,4
276,"Saint Helena, Ascension and Tristan da Cunha",United Kingdom,-7.946700,-14.355900,0,0,0,0,0,0,...,2166,2166,2166,2166,2166,2166,2166,2166,2166,2166
277,Turks and Caicos Islands,United Kingdom,21.694000,-71.797900,0,0,0,0,0,0,...,6551,6551,6551,6551,6551,6551,6551,6557,6557,6561
278,NaN,United Kingdom,55.378100,-3.436000,0,0,0,0,0,0,...,24370150,24370150,24396530,24396530,24396530,24396530,24396530,24396530,24396530,24425309

In [64]:
df["Country/Region"].isnull().value_counts()

Country/Region
False    289
Name: count, dtype: int64

In [65]:
df["Lat"].isnull().value_counts()

Lat
False    287
True       2
Name: count, dtype: int64

In [66]:
df["Long"].isnull().value_counts()

Long
False    287
True       2
Name: count, dtype: int64

In [67]:
df[df["Long"].isnull() == True]

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,2/28/23,3/1/23,3/2/23,3/3/23,3/4/23,3/5/23,3/6/23,3/7/23,3/8/23,3/9/23
53,Repatriated Travellers,Canada,NaN,NaN,0,0,0,0,0,0,...,13,13,13,13,13,13,13,13,13,13
89,Unknown,China,NaN,NaN,0,0,0,0,0,0,...,1521816,1521816,1521816,1521816,1521816,1521816,1521816,1521816,1521816,1521816

In [68]:
date_cols = df.columns[4:]
daily = df[date_cols].diff(axis = 1)
daily.head(5)

C:\Users\THEKIET\AppData\Local\Temp\ipykernel_21936\3003581777.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  daily = df[date_cols].diff(axis = 1)

,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,1/28/20,1/29/20,1/30/20,1/31/20,...,2/28/23,3/1/23,3/2/23,3/3/23,3/4/23,3/5/23,3/6/23,3/7/23,3/8/23,3/9/23
0,NaN,0,0,0,0,0,0,0,0,0,...,14,18,18,4,7,21,16,30,15,0
1,NaN,0,0,0,0,0,0,0,0,0,...,11,17,0,19,0,0,0,0,16,14
2,NaN,0,0,0,0,0,0,0,0,0,...,1,7,15,6,0,8,0,13,4,2
3,NaN,0,0,0,0,0,0,0,0,0,...,0,9,0,0,0,0,0,0,15,0
4,NaN,0,0,0,0,0,0,0,0,0,...,0,22,0,0,0,0,0,0,11,0

In [69]:
mask_neg = (daily < 0).any(axis = 1)
df[mask_neg][['Province/State', 'Country/Region']]

                   Province/State       Country/Region
0                             NaN          Afghanistan
6                             NaN  Antigua and Barbuda
9    Australian Capital Territory            Australia
10                New South Wales            Australia
11             Northern Territory            Australia
..                            ...                  ...
278                           NaN       United Kingdom
279                           NaN              Uruguay
281                           NaN              Vanuatu
286                           NaN                Yemen
288                           NaN             Zimbabwe

[128 rows x 2 columns]

In [70]:
daily = daily.clip(0)
(daily < 0).any(axis = 1).value_counts()

False    289
Name: count, dtype: int64

In [71]:
df.duplicated().sum()

np.int64(0)

In [72]:
df.duplicated(subset=['Province/State', 'Country/Region']).sum()

np.int64(0)

In [73]:
df.duplicated(date_cols).sum()

np.int64(0)

In [76]:
country_cumulative = df.groupby("Country/Region")[date_cols].sum()
country_cumulative.sort_values("3/9/23", ascending=False).head(10)

,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,1/28/20,1/29/20,1/30/20,1/31/20,...,2/28/23,3/1/23,3/2/23,3/3/23,3/4/23,3/5/23,3/6/23,3/7/23,3/8/23,3/9/23
Country/Region,,,,,,,,,,,,,,,,,,,,,
US,1,1,2,2,5,5,5,6,6,8,...,103443455,103533872,103589757,103648690,103650837,103646975,103655539,103690910,103755771,103802702
India,0,0,0,0,0,0,0,0,1,1,...,44687837,44688105,44688388,44688722,44689046,44689327,44689593,44689919,44690298,44690738
France,0,0,2,3,3,3,4,5,5,5,...,39827175,39831700,39835896,39839090,39839090,39839090,39847236,39854299,39860410,39866718
Germany,0,0,0,0,0,1,4,4,4,5,...,38168908,38189954,38202571,38210850,38210850,38210851,38210851,38231610,38241231,38249060
Brazil,0,0,0,0,0,0,0,0,0,0,...,37052936,37063464,37063464,37081209,37081209,37081209,37076053,37076053,37076053,37076053
Japan,2,2,2,2,4,4,7,7,11,15,...,33227230,33241180,33252686,33263208,33273639,33282370,33286633,33298799,33310604,33320438
"Korea, South",1,1,2,2,3,4,4,4,4,11,...,30526012,30533573,30543981,30555102,30555102,30569215,30581499,30594297,30605187,30615522
Italy,0,0,0,0,0,0,0,0,0,2,...,25576852,25576852,25576852,25603510,25603510,25603510,25603510,25603510,25603510,25603510
United Kingdom,0,0,0,0,0,0,0,0,0,2,...,24603373,24603450,24629830,24629840,24629840,24629840,24629840,24629846,24629922,24658705
Russia,0,0,0,0,0,0,0,0,0,2,...,21960719,21974098,21988110,22002485,22016406,22029824,22040875,22051220,22063473,22075858